// try-catch-finally

public class exception {
    public static void main(String[] args) {

        

    }
}